# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-22 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectroles', '0011_remove_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotesite',
            name='user_display',
            field=models.BooleanField(default=1, help_text='RemoteSite visibility to users'),
        ),
    ]
