# Generated by Django 3.1.7 on 2021-02-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectroles', '0017_project_full_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsetting',
            name='value_json',
            field=models.JSONField(default=dict, help_text='Optional JSON value for the setting', null=True),
        ),
    ]
