# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-11 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sodarprojectcache', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsoncacheitem',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Project in which the item belongs', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cached_items', to='projectroles.Project'),
        ),
    ]
