# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-13 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sodarprojectcache', '0002_auto_20190311_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jsoncacheitem',
            old_name='app',
            new_name='app_name',
        ),
    ]
