# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-18 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sodarprojectcache', '0004_auto_20190318_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jsoncacheitem',
            old_name='app_nam',
            new_name='app_name',
        ),
    ]
