# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-27 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectroles', '0006_add_remote_projects'),
        ('sodarprojectcache', '0005_auto_20190318_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsoncacheitem',
            name='name',
            field=models.CharField(help_text='Name or title of the item given by the data setting app', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='jsoncacheitem',
            unique_together=set([('project', 'app_name', 'name')]),
        ),
    ]
